"""Inicializacao do banco

Revision ID: 04feafd96860
Revises: 
Create Date: 2019-08-04 12:58:10.059567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04feafd96860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'autor',
        sa.Column('id_autor', sa.Integer, autoincrement=True, nullable=False, primary_key=True),
        sa.Column('autor', sa.String, nullable=False),
    )

    op.create_table(
        'categoria',
        sa.Column('id_categoria', sa.Integer, autoincrement=True, nullable=False, primary_key=True),
        sa.Column('categoria', sa.String, nullable=False),
    )

    op.create_table(
        'frase',
        sa.Column('id_frase', sa.Integer, autoincrement=True, nullable=False, primary_key=True),
        sa.Column('frase', sa.String, nullable=True),
        sa.Column('id_autor', sa.Integer, sa.ForeignKey("autor.id_autor"), nullable=False),
        sa.Column('id_categoria', sa.Integer, sa.ForeignKey("categoria.id_categoria"),nullable=False),
        sa.Column('date_created', sa.DateTime, nullable=False),
        sa.Column('usado', sa.Boolean, nullable=True)
    )

    op.create_table(
        'profissao_autor',
        sa.Column('id_profissao_autor', sa.Integer, autoincrement=True, nullable=False, primary_key=True),
        sa.Column('profissao_autor', sa.String, nullable=False),
    )

    # id_profissao_autor = Column(Integer)
    # id_autor = Column(Integer)
    op.create_table(
        'profissoes_autores',
        sa.Column('id_autor', sa.Integer, sa.ForeignKey('autor.id_autor'), nullable=False),
        sa.Column('id_profissao_autor', sa.Integer, sa.ForeignKey('profissao_autor.id_profissao_autor'),nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for tabela in ('autor', 'categoria', 'frase', 'profissao_autor', 'profissoes_autores'):
        op.drop_table(tabela)
    # ### end Alembic commands ###
