"""Adição de pk em profissoes_autores

Revision ID: 33f36d115d9b
Revises: 04feafd96860
Create Date: 2019-08-04 16:23:19.932578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33f36d115d9b'
down_revision = '04feafd96860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_primary_key(
            "pk_profissoes_autores", "profissoes_autores",
            ["id_profissao_autor", "id_autor"]
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_profissoes_autores', 'profissoes_autores', type_='primary')
    # ### end Alembic commands ###
